### ISSUE TITLE
Completed callback

### ISSUE THREAD

**Issue by PaulieScanlon** [PaulieScanlon/node-tiny-template#11]
Might also be quite handy to have a completed callback for when Tiny Template has finished it can trigger other scripts.

Maybe the callback is a key in the config object and accepts a param for the name of a node script to call?

**Comment by bnwan** [comment]
Agree...sounds like a good idea...or it could return a promise which will then allow for chaining

**Comment by PaulieScanlon** [comment]
@bnwan take a look at PR #13
